### ISSUE TITLE
Unable to start service

### ISSUE THREAD

**Issue by psnider** [rjrodger/nodezoo-index#1]
I'm trying to set up nodezoo on my Mac.
I already have these running:
- nodezoo using `node srvs/npm-dev.js --seneca.log=plugin:npm`
- elasticsearch using `elasticsearch`
- redis from a built install with `src/redis-server`

When I try to start nodezoo-index using `node srvs/index-dev.js`, I get the following error:

```
RAW-ENTRY { level: 'info+', handler: 'print' }
/Users/peter/devel/tutorials/nodezoo-index/node_modules/seneca/lib/logging.js:230
      handler.routestr = routestr
                       ^
TypeError: Cannot assign to read only property 'routestr' of print
    at /Users/peter/devel/tutorials/nodezoo-index/node_modules/seneca/lib/logging.js:230:24
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/peter/devel/tutorials/nodezoo-index/node_modules/seneca/node_modules/underscore/underscore.js:79:11)
    at exports.makelogroute (/Users/peter/devel/tutorials/nodezoo-index/node_modules/seneca/lib/logging.js:225:5)
    at /Users/peter/devel/tutorials/nodezoo-index/node_modules/seneca/lib/logging.js:124:7
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/peter/devel/tutorials/nodezoo-index/node_modules/seneca/node_modules/underscore/underscore.js:79:11)
    at Object.exports.makelogrouter (/Users/peter/devel/tutorials/nodezoo-index/node_modules/seneca/lib/logging.js:116:5)
    at make_seneca (/Users/peter/devel/tutorials/nodezoo-index/node_modules/seneca/lib/seneca.js:241:32)
    at init (/Users/peter/devel/tutorials/nodezoo-index/node_modules/seneca/lib/seneca.js:1924:16)
```

Note that I enabled the debug message at the start of makelogroute().
I get similar errors when trying to start any of the other servers.

Also, the docs don't mention how to start the server, so I hope I'm doing it the right way.

**Comment by psnider** [comment]
Here are the versions of the tools that I'm using:

```
$ node --version
v0.12.7

$ npm list --depth 0
nodezoo-index@0.1.0 /Users/peter/devel/tutorials/nodezoo-index
├── mocha@1.21.5
├── request@2.61.0
├── seneca@0.5.21
├── seneca-beanstalk-transport@0.1.1
└── seneca-redis-transport@0.1.1
```

**Comment by thefoxis** [comment]
+1, there's no "how to run" instructions at all and based on the activity it seems questionable whether it's still a requirement to use it.
